# ESTO ES UN COMENTARIO
# Todo lo que está a la derecha de # es solo para nosotros

version: 0.3.5 # NO TOCAR

# HODL username
# username: "USUARIO" # < TU_USUARIO@hodl.ar

# NOSTR Settings
# nostr: # Sin el # adelante
#   npub: "TU_PUB" # Entre comillas dobles

# Configuración Global
html:
# title: Este valor no funciona porque esta comentado
  title: Links | Nextdoor # Este es el Título que aparece en la pestaña de navegador

# Colores de plantilla
theme:
  background_color: "#f9fafb"
  # cover_color: "#ff7070"

# Configuración Central
main:
  title: Nextdoor # Aca podes poner tu nombre o el de tu producto

# Lista de bloques
blocks:
  # Estos bloques los podes editar cambiando SOLO el texto que está en blanco
  # Sacale 

  - title: Instagram
    icon: instagram
    url: https://www.instagram.com/next.door_/

  - title: Twitter
    icon: twitter
    url: https://twitter.com/NextDoor95

  - title: LinkedIn # Este es el nombre del botón
    icon: linkedin # Este es el nombre del icono (si queres añadir una red social nueva, prestá atencion que es todo con minúscula)
    url: https://www.linkedin.com/in/nextdoor-frontend/ # Link a donde redireccionará al hacer click

  - title: Github
    icon: github
    url: https://github.com/NextDoor95

  - title: Sitio Web
    icon: url
    url: https://nextdoor95.github.io/PortfolioWeb/

  - title: Telegram
    icon: telegram
    url: https://t.me/NextDoor95
    
# Guardá el archivo haciendo click en Commit Changes, abajo
# Volvé a las instrucciones
